apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dynamo
resources:
  - namespace.yaml
  - crds-helmrelease.yaml
  - platform-helmrelease.yaml
  # Grove is included in dynamo-platform as a dependency
  # Model deployments
  - model-storage-pvc.yaml
  - gpt-oss-20b-graph.yaml
  - ingress.yaml
