apiVersion: v1
kind: Service
metadata:
  name: nginx-example
  namespace: default
  labels:
    app: nginx-example
spec:
  type: ClusterIP
  selector:
    app: nginx-example
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
