apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - secret.enc.yaml
  - oauth-secret.enc.yaml
  - prometheus-helmrelease.yaml
  - grafana-helmrelease.yaml
  - ingress.yaml
  - certificate.yaml
  - prometheus-ingress.yaml
