apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vllm
resources:
  - namespace.yaml
  - model-storage-pvc.yaml
  - hf-token-secret.enc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
