apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - configmap.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
commonLabels:
  app.kubernetes.io/name: web-app-example
  app.kubernetes.io/managed-by: flux
